DROP TABLE IF EXISTS todos;

CREATE TABLE todos (
   id INT AUTO_INCREMENT PRIMARY KEY,
   parentId INT DEFAULT NULL,
   description VARCHAR(255) NOT NULL,
   createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
   deadline DATETIME NOT NULL,
   isDone BOOL DEFAULT FALSE
);

CREATE TABLE users (
   id INT AUTO_INCREMENT PRIMARY KEY,
   username VARCHAR(255) NOT NULL,
   password VARCHAR(255) NOT NULL
);
